name: Release on Tag
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Build
        run: zip -r build.xpi background.js icon*.svg LICENSE manifest.json modal options
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{1bab54e2-6c60-4ee1-88f7-52b1df77924f}'
          xpi: build.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
